trigger:
  branches:
    include:
      - main 

pool:
  name: 'prueba'

jobs:
- job: RunCartTestsParallel
  displayName: 'Ejecutar pruebas paralelas de CartTests'
  steps:
    - checkout: self  
    - script: mvn clean test -Dtest=CartTestParalelas 
      displayName: 'Ejecutar CartTestParalelas'
      workingDirectory: '$(System.DefaultWorkingDirectory)' 

    # Paso de post-procesamiento para almacenar los resultados de las pruebas
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'  
        testResultsFiles: '**/target/surefire-reports/*.xml'  
        failOnEmptyTestResults: true  
      displayName: 'Publicar resultados de pruebas CartTestParalelas'


