trigger:
  branches:
    include:
      - main 

pool:
  vmImage: 'windows-latest'  

jobs:
- job: RunCartTests
  displayName: 'Ejecutar pruebas de CartTests'
  steps:
    - checkout: self 
    - script: mvn clean test -Dtest=CartTests -Dbase.url=https://fd5a-190-67-141-159.ngrok-free.app
      displayName: 'Ejecutar CartTests'
      workingDirectory: '$(System.DefaultWorkingDirectory)' 

    # Paso de post-procesamiento para almacenar los resultados de las pruebas
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'  
        testResultsFiles: '**/target/surefire-reports/*.xml'  
        failOnEmptyTestResults: true  
      displayName: 'Publicar resultados de pruebas CartTests'

- job: RunCartTestsParallel
  displayName: 'Ejecutar pruebas paralelas de CartTests'
  steps:
    - checkout: self  
    - script: mvn clean test -Dtest=CartTestParalelas -Dbase.url=https://fd5a-190-67-141-159.ngrok-free.app
      displayName: 'Ejecutar CartTestParalelas'
      workingDirectory: '$(System.DefaultWorkingDirectory)' 

    # Paso de post-procesamiento para almacenar los resultados de las pruebas
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'  
        testResultsFiles: '**/target/surefire-reports/*.xml'  
        failOnEmptyTestResults: true  
      displayName: 'Publicar resultados de pruebas CartTestParalelas'

- job: SimulateError
  displayName: 'Simular error 500'
  dependsOn: RunCartTests
  steps:
    - checkout: self 
    - script: mvn test -Dtest=Error500CartTest -Dbase.url=https://fd5a-190-67-141-159.ngrok-free.app
      displayName: 'Ejecutar prueba de error 500'
      workingDirectory: '$(System.DefaultWorkingDirectory)' 

    # Paso de post-procesamiento para almacenar los resultados de las pruebas de error
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'  
        testResultsFiles: '**/target/surefire-reports/*.xml'  
        failOnEmptyTestResults: true  
      displayName: 'Publicar resultados de prueba de error 500'
